Add remove endpoint
AndreyAvdoshin/java-filmorate pull request #10
Opened 2023-11-30 19:14 UTC by cayoskoro

- Добавлен эндпоинта удаления сущностей в абстрактном классе
- Добавлено исключение NotAllowedException для ресурсов без эндпоинта удаления
- Добавлен метод удаления в сервисных слоях
- Добавлен метод удаления в репозиториях
- Добавлены юнит тесты удаления для пользователей, фильмов

2023-12-01 13:33 UTC, AndreyAvdoshin requested changes

2023-12-01 13:33 UTC, AndreyAvdoshin commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "ORDER BY films.release_date ASC";
По всей видимости от таблички director можно отказаться в запросе

2023-12-01 14:38 UTC, cayoskoro commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +                "ORDER BY d.id";
Готово.
Итоговый вариант:
SELECT d.*
FROM directors d, film_director fd
WHERE d.id = fd.director_id AND fd.film_id = ?
ORDER BY d.id

2023-12-01 14:38 UTC, cayoskoro commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "ORDER BY films.release_date ASC";
Готово.
Итоговый вариант:
SELECT films.*, mpa.* 
FROM film_director fd 
LEFT JOIN films ON fd.film_id = films.id 
INNER JOIN mpa ON films.mpa_id = mpa.id 
WHERE fd.director_id = ?
ORDER BY films.release_date ASC

2023-12-02 06:50 UTC, AndreyAvdoshin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                       Storage<Director> directorDbStorage) {
Здесь, на мой взгляд, дополнительные хранилища должны быть объявлены их классами, а не базовым. Давай объявление Базового класса оставим для основного хранилища.

2023-12-02 07:22 UTC, AndreyAvdoshin approved these changes

2023-12-02 10:29 UTC, soursager approved these changes

2023-12-02 10:29 UTC, soursager commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +        throw new NotAllowedException("Метод не разрешен для данного ресурса");
Задел на будущее, посмотрим, как на это отреагирует ревьюер)

2023-12-02 10:29 UTC, soursager commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDbStorage.java
> +        return new HashSet<>(jdbcTemplate.query(sql, new BeanPropertyRowMapper<>(Director.class), id));
Отличное решение!

2023-12-02 10:29 UTC, soursager commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                film.getId());
Так выглядит лучше и более читаемо.

2023-12-02 10:35 UTC, merged